version: "3.8"


volumes:
  restaurant-db-data:
    name: restaurant-db-volume

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.23
    container_name: restaurant-core-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - restaurant-db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 3

  restaurant-core:
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "1"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s